### PR TITLE
WIP - Add pawn and king move candidates

### PR DESCRIPTION
**Pull request by DenysLins**
Add pawn candidate squares move - Issue https://github.com/programarivm/redux-chess/issues/4

Screenshot from 2021-06-30 22-47-09

Screenshot from 2021-06-30 22-46-48

### CODE REVIEW

**Comment by programarivm** [comment]
@DenysLins thanks a lot for the work, it's very much appreciated!

At this moment I still wouldn't be too clear about this issue if we want to keep the chessboard as lightweight as it can possibly be. 

So for example, what about the possible moves of other pieces? 

It seems as if highlighting the possible moves means implementing kind of a validation logic on the frontend side too, as I did before as explained in this post:

- [Converting a FEN Chess Position Into a PGN Move](https://medium.com/geekculture/converting-a-fen-chess-position-into-a-pgn-move-4a278d81b21f)

> It seemed to me that playing around with PGN moves on the frontend side of things would make sense, and as a result I wrote something like a pseudo-PGN validation in a JavaScript file.

The possible moves are implemented on the server side instead, so what about adding a command for this?

Thank you, and happy learning and coding!

**Comment by DenysLins** [comment]
I understand your point. I can't find the method that you referenced in the php-chess documentation. Can you guide me?

**Comment by programarivm** [comment]
It seems as if the chess server would need an update to include a new command.

If this is okay, let me give you a ping after that one is completed.

See https://github.com/programarivm/chess-server/issues/6

**Comment by DenysLins** [comment]
Ok. Please let me know when you finish

**Comment by programarivm** [comment]
@DenysLins what about adding a `const piece` to [actions/serverActions.js](https://github.com/programarivm/redux-chess/blob/master/src/actions/serverActions.js) to send a new WebSocket message?

See https://github.com/programarivm/chess-server/issues/6

**Comment by programarivm** [comment]
@DenysLins thanks for the the help, this one wasn't too obvious at all.

See closed issue https://github.com/programarivm/redux-chess/issues/34

**Pull request closed without merging**
